### ISSUE TITLE
No ISO codes for list of counties

### ISSUE THREAD

**Issue by elitemaks** [AnthonyEbert/COVID-19_ISO-3166#1]
Here is a list of countries missing from the list.
Some of them are currently listed as Provinces under other countries, like St Martin - in the last CSVs it's under France, but in previous CSVs it's a separate country, so probably it worth adding it as it helps to work with historical data.

'Hong Kong' => 'HKG',
'Jersey' => 'JEY',
'Guernsey' => 'GGY',
'Congo (Brazzaville)' => 'COG',
'Kosovo' => 'RKS',
'Saint Vincent and the Grenadines' => 'VCT',
'Taiwan' => 'TWN',
'Palestine' => 'PSE',
'Vatican City' => 'VAT',
'St. Martin' => 'MAF'

**Comment by AnthonyEbert** [comment]
Thanks! see 772f4e341bad3d343f66c1b750fbe5270b4c1fb9
